services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE_NAME=mysql
    volumes:
      - ./.docker/mysql:/var/lib/mysql/data